### ISSUE TITLE
Any support for ArangoDB

### ISSUE THREAD

**Issue by bitsnaps** [paulk-asert/groovy-graphdb#2]
Hi,

It's also possible to include ArangoDB thourgh it's official [Java Driver](https://github.com/arangodb/arangodb-java-driver)?
Any serious benchmark?

**Comment by paulk-asert** [comment]
It certainly is possible to support ArangoDB. In fact I was planning to also include it in the blog post but the community edition experience wasn't ideal. The tutorial required registration and the code examples link seemed broken:
https://github.com/arangodb/arangodb-java-driver/tree/main/driver/src/test/java/com/arangodb/example
(Link from https://docs.arangodb.com/3.11/develop/drivers/java/)

In terms of benchmarking, it really boils down to the graph database speed. Groovy with compile static (optionally with GraalVM) has a similar speed to Java. If using lots of dynamic features, Groovy adds a small overhead compared to Java.

**Comment by bitsnaps** [comment]
Unfortunately the newer version seems to be using different API. I [arangodb-demo](https://github.com/bitsnaps/arangodb-demo) as an example using older community edition version without any registration that time.
